on: [push, pull_request]
name: Formatting on nightly toolchain
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt -- --check
      - name: Check formatting on fuzzing
        run: cargo fmt --manifest-path fuzz/Cargo.toml -- --check
