on: [push, pull_request]
name: Build fuzz targets on nightly toolchain
jobs:
  build_fuzzing:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo fuzz
        run: cargo install cargo-fuzz
      - name: Build fuzz targets
        run: cargo fuzz build
