on: [push, pull_request]
name: Lints on stable toolchain
jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Check Clippy lints
        run: cargo clippy -- -W clippy::match-same-arms
      - name: Check Clippy lints on tests
        run: cargo clippy --tests -- -W clippy::match-same-arms
      - name: Check Clippy lints on fuzzing
        run: cargo clippy --manifest-path fuzz/Cargo.toml -- -W clippy::match-same-arms
