on: [push, pull_request]
name: Lints on stable toolchain
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Check formatting on fuzzing
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path fuzz/Cargo.toml -- --check

      - name: Check Clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -W clippy::match-same-arms

      - name: Check Clippy lints on tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests -- -D warnings -W clippy::match-same-arms

      - name: Check Clippy lints on fuzzing
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path fuzz/Cargo.toml -- -D warnings -W clippy::match-same-arms
